name: IntegrationTest

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    strategy:
      matrix:
        version: [ "3.6", "3.9" ]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Test with pytest
        run: |
          python -m pytest -x -s tests/integration/
