# This workflow will install Python dependencies and run tests
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: UnitTests

on:
  pull_request:    
    branches:
      - main
      - develop

jobs:
  test:
    strategy:
      matrix:
        version: ["3.6", "3.9"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
    - name: Test with pytest
      run: |
        coverage run --source db_plugins --omit db_plugins/db/sql/serializers.py -m pytest tests/unittest/
        coverage xml
    - name: Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
